export const Colors = {
  background: "#f7f9fb",
  primary: "#0058be",
  onPrimary: "#ffffff",
  primaryFixed: "#d8e2ff",
  primaryContainer: "#e0f2fe",
  surface: "#ffffff", // For cards
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f2f4f6",
  surfaceContainer: "#eceef0",
  surfaceContainerHigh: "#e6e8ea",
  surfaceContainerHighest: "#e0e3e5",
  onBackground: "#191c1e",
  onSurface: "#191c1e",
  surfaceVariant: "#f1f5f9",
  onSurfaceVariant: "#424754",
  outlineVariant: "#c2c6d6",
  outline: "#727785",
  secondaryContainer: "#d0e1fb",
  onSecondaryContainer: "#54647a",
  tertiaryContainer: "#b75b00",
  onTertiaryContainer: "#fffbff",
};
