import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0058be", // Ensure top area matches header if outside safe area
  },
  container: {
    flex: 1,
    backgroundColor: "#f7f9fb",
  },
  content: {
    padding: 16,
    paddingBottom: 32,
    gap: 24,
  },
  profileCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: "rgba(194, 198, 214, 0.3)",
    overflow: "hidden",
    position: "relative",
    marginBottom: 16,
  },
  profileBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "33%",
    backgroundColor: "rgba(208, 225, 251, 0.5)",
  },
  avatarContainer: {
    position: "relative",
    width: 96,
    height: 96,
    marginBottom: 8,
    borderRadius: 48,
    borderWidth: 4,
    borderColor: "#ffffff",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  avatar: {
    width: "100%",
    height: "100%",
    borderRadius: 48,
  },
  editAvatarButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#0058be",
    padding: 6,
    borderRadius: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  userName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#191c1e",
    zIndex: 10,
    marginBottom: 4,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(183, 91, 0, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    zIndex: 10,
    gap: 4,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#924700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  gridContainer: {
    gap: 16,
  },
  listItemValueText: {
    fontSize: 14,
    color: "#424754",
  },
  toggleGroup: {
    flexDirection: "row",
    backgroundColor: "#e0e3e5",
    padding: 4,
    borderRadius: 8,
    gap: 4,
  },
  toggleBtn: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 4,
  },
  toggleBtnActive: {
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  toggleBtnText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#424754",
  },
  toggleBtnTextActive: {
    fontSize: 12,
    fontWeight: "500",
    color: "#191c1e",
  },
});
